name: 'Blog Custom Github Action'
description: 'Call an API and get the result'
runs:
  using: "composite"
  steps:
    - name: update go deps
      shell: bash
      run: |
        go mod tidy \
        go get -modfile=go.mod -d -d -u -t ./...  \
        go mod tidy
