name: 'Update all go dependencies'
description: 'Update all go dependencies'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: go mod tidy
    - shell: bash
      run: go get -modfile=go.mod -d -d -u -t ./...
    - shell: bash
      run: go mod tidy
