name: 'Blog Custom Github Action'
description: 'Call an API and get the result'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: go mod tidy
    - shell: bash
      run: go get -modfile=go.mod -d -d -u -t ./...
    - shell: bash
      run: go mod tidy
